spring:
  session:
    timeout: 5m

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG