spring:
  data:
    redis:
      host: localhost
      port: 6379

  session:
    timeout: 30d

  mvc:
    dispatch-trace-request: true

  web:
    resources:
      add-mappings: false

  application:
    name: file-storage-api

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        format_sql: false
        show_sql: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

minio:
  rootBucket: users
  url: http:/localhost:9000
  credentials:
    accessKey: yarik
    secretKey: 12345678
storage:
  max-size-bytes: 1073741824