spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG