spring:
  session:
    timeout: 30d

  mvc:
    dispatch-trace-request: true

  web:
    resources:
      add-mappings: false

  application:
    name: file-storage-api

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl:
          auto: none

  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

minio:
  rootBucket: ${ROOT_BUCKET}
  url: ${MINIO_URL}
  credentials:
    accessKey: ${MINIO_ACCESS_KEY}
    secretKey: ${MINIO_SECRET_KEY}